import asyncio
import os
from datetime import datetime
from pathlib import Path


async def write_report(
    filename: str,
    title: str,
    executive_summary: str,
    key_findings: list[str],
    detailed_analysis: str,
    sources: list[str],
    confidence: str,
) -> str:
    reports_dir = Path(os.environ.get("REPORTS_DIR", "./reports"))
    await asyncio.to_thread(reports_dir.mkdir, parents=True, exist_ok=True)

    safe_name = Path(filename).name
    if not safe_name.endswith(".md"):
        safe_name += ".md"

    output_path = reports_dir / safe_name
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M")

    findings_md = "\n".join(f"- {f}" for f in key_findings)
    sources_md = "\n".join(f"- {s}" for s in sources)

    body = f"""\
# {title}

_Generated by Sift on {timestamp} · Confidence: **{confidence}**_

---

## Executive Summary

{executive_summary}

---

## Key Findings

{findings_md}

---

## Detailed Analysis

{detailed_analysis}

---

## Sources

{sources_md}
"""

    await asyncio.to_thread(output_path.write_text, body, encoding="utf-8")
    return f"Report written to {output_path.resolve()}"
